name: Publish Site

on:
  push:
    branches:
      - main
         # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Publish Site
        uses: kubewarden/hugo-gh-pages@fix-publishing
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
